-- ALTER SYSTEM SET SGA_TARGET=500G SCOPE=SPFILE;
-- ALTER SYSTEM SET INMEMORY_SIZE=300G SCOPE=SPFILE;
-- SHUTDOWN IMMEDIATE;
-- STARTUP;

CREATE TABLE Reviews_ColStore_Query_High (
    ReviewID INT PRIMARY KEY,
    ReaderID INT,
    BookID INT,
    Rating INT CHECK (Rating >= 1 AND Rating <= 5),
    ReviewText VARCHAR(1000),
    ReviewDate DATE NOT NULL,
    FOREIGN KEY (ReaderID) REFERENCES Readers(ReaderID),
    FOREIGN KEY (BookID) REFERENCES Books(BookID)
)
TABLESPACE Exadata_tablespace
COMPRESS FOR OLTP;

SELECT 
    TABLESPACE_NAME, 
    FILE_NAME, 
    BYTES / (1024 * 1024) AS SIZE_MB
FROM 
    DBA_DATA_FILES
ORDER BY 
    TABLESPACE_NAME;
        
CREATE TABLESPACE Exadata_Tablespace 
DATAFILE 'C:\APP\ADAMS\PRODUCT\21C\CFGTOOLLOGS\DBCA\ORADATA\XE\XEPDB1\TEST01.DBF'
SIZE 600M 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO;

SELECT table_name, compression
FROM dba_tables;

ALTER TABLE Reviews
   MOVE NOCOMPRESS;

ALTER TABLE Reviews
   MOVE COMPRESS FOR OLTP;
--    QUERY HIGH, OLTP, BASIC;
SELECT * FROM Reviews;

CREATE TABLE ala_ma_kota(
    ReaderID INT,
    BookID INT
)

ALTER TABLE ala_ma_kota
   MOVE COMPRESS FOR QUERY LOW;

CREATE TABLE sales (
    sale_id NUMBER,
    sale_date DATE,
    amount NUMBER,
    region VARCHAR2(50)
) 
INMEMORY;

ALTER TABLE sales
   MODIFY (amount INMEMORY);
DROP TABLE sales;
CREATE TABLE sales (
    sale_id NUMBER,
    sale_date DATE,
    amount NUMBER,
    region VARCHAR2(50)
)

PARTITION BY RANGE (sale_date) 
(
    PARTITION p1 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')) 
    COMPRESS FOR QUERY HIGH,
    PARTITION p2 VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD')) 
    COMPRESS FOR QUERY LOW
);